############################################################################
#
#  Nix commands related to the local machine
#
############################################################################

sync:
  ~/.config/just/sync.sh

syncHome:
  ~/.config/just/sync-home.sh

syncSystem:
  ~/.config/just/sync-system.sh
